use std::fs;
use crate::core::utils::{detect_chassis, ChassisKind};

pub fn ensure_user_config_exists() -> std::io::Result<()> {
    if let Some(mut path) = dirs::home_dir() {
        path.push(".config/stasis");
        
        // Create directory if missing
        if !path.exists() {
            fs::create_dir_all(&path)?;
        }
        
        // Append file name
        path.push("stasis.rune");
        
        // If file exists, do nothing
        if path.exists() {
            return Ok(());
        }
        
        // Otherwise, generate initial config
        let contents = generate_default_config();
        fs::write(&path, contents)?;
        println!("Stasis: Default config created at {:?}", path);
    }
    Ok(())
}

fn generate_default_config() -> String {
    match detect_chassis() {
        ChassisKind::Laptop => default_laptop_config(),
        ChassisKind::Desktop => default_desktop_config(),
    }
}

fn default_laptop_config() -> String {
    r#"
# This file was auto-generated by Stasis on first run
# Feel free to customize it to your needs
# Master config reference: `/etc/stasis/stasis.rune`

@author "Dustin Pilgrim"
@description "Lightweight feature packed idle manager for Wayland"

stasis:
  monitor_media true
  # Stop remote media from affecting pause
  ignore_remote_media true
  respect_idle_inhibitors true
  # Uncomment to customized debounce, default is 0
  # debounce_seconds 4
  
  inhibit_apps [
    "vlc"
    "mpv"
    r"steam_app_.*"
  ]
  
  # Laptop-specific: AC power settings (relaxed timeouts)
  on_ac:
    brightness:
      timeout 300 # 5 minute(s)
      command "brightnessctl set 50%"
    end
    
    dpms:
      timeout 120 # 2 minute(s) after brightness
      command "niri msg action power-off-monitors"
      resume-command "niri msg action power-on-monitors"
    end
    
    lock_screen:
      timeout 180 # 3 minute(s) after dpms
      command "swaylock"
    end
    
    suspend:
      timeout 600 # 10 minute(s) after lock
      command "systemctl suspend"
    end
  end
  
  # Laptop-specific: Battery power settings (aggressive power saving)
  on_battery:
    brightness:
      timeout 60 # 1 minute(s)
      command "brightnessctl set 30%"
    end
    
    dpms:
      timeout 30 # 30 second(s) after brightness
      command "niri msg action power-off-monitors"
      resume-command "niri msg action power-on-monitors"
    end
    
    lock_screen:
      timeout 60 # 1 minute(s) after dpms
      command "swaylock"
    end
    
    suspend:
      timeout 120 # 2 minute(s) after lock
      command "systemctl suspend"
    end
  end
end
"#
    .trim_start()
    .to_string()
}

fn default_desktop_config() -> String {
    r#"
# This file was auto-generated by Stasis on first run
# Feel free to customize it to your needs
# Master config reference: `/etc/stasis/stasis.rune`

@author "Dustin Pilgrim"
@description "Lightweight feature packed idle manager for Wayland"

stasis:
  monitor_media true
  # Stop remote media from affecting pause
  ignore_remote_media true
  respect_idle_inhibitors true
  # Uncomment to lock screen on lid close
  #lid_close_action "lock-screen"
  # Uncomment to customized debounce, default is 0
  # debounce_seconds 4

  inhibit_apps [
    "vlc"
    "mpv"
    r"steam_app_.*"
  ]
  
  lock_screen:
    timeout 300 # 5 minute(s)
    command "swaylock"
  end
  
  dpms:
    timeout 60 # 1 minute(s) after lock
    command "niri msg action power-off-monitors"
    resume-command "niri msg action power-on-monitors"
  end
  
  suspend:
    timeout 1800 # 30 minute(s) after dpms
    command "systemctl suspend"
  end
end
"#
    .trim_start()
    .to_string()
}
